<?php
/**
 * Copyright © ...
 */

use Block\Page;
$block = new Page();
?>
<div class="item mt-5">
    <h3><?= $block->getSearchFormTitle(); ?></h3>
    <form action="<?= $block->getUrl(); ?>" class="search-customer col-12 mx-auto mt-2" method="POST">
        <div class="row">
            <div class="col form-group">
                <input type="text" class="username form-control" name="username" placeholder="Username" aria-label="Username" value="" />
            </div>
            <div class="col form-group">
                <input type="hidden" class="form-control" name="crud" value="search" />
                <button type="submit" class="btn btn-primary search">Submit</button>
                <a href="/" class="btn btn-primary search">Show All</a>
            </div>
        </div>
    </form>

</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        new $.workWithCustomer();
    })
</script>
